version: "2"
virtualmachines:
- name: workstation
  image: instruqt-hashicorp/terraform-workstation-prod
  shell: /bin/bash
  environment:
    ARM_SUBSCRIPTION_ID: 14692f20-9428-451b-8298-102ed4e39c2a
    ARM_TENANT_ID: 0e3e2e88-8caf-41ca-b4da-e3b33b6c52ec
    VAULT_ADDR: https://cam-vault.hashidemos.io:8200
    VAULT_CREDS_ENDPOINT: azure/creds/se-training-workstation
    VAULT_NAMESPACE: Sales/SE
  machine_type: n1-standard-1
